### ISSUE TITLE
Missing Related Work: ShareDB

### ISSUE THREAD

**Issue by curran** [JoshData/jot#11]
Greetings! Very nice work here. I noticed you have a related work section, so I wanted to let you know about the following related projects:

 * https://github.com/ottypes/json0
 * https://github.com/share/sharedb

**Comment by JoshData** [comment]
Thanks!! I recently came across them and had been intending to add them.

**Comment by curran** [comment]
Nice! I've been using ShareDB for some time, and I was delighted to come across your work here. Always interesting to see a fresh take on JSON OT.
