### ISSUE TITLE
"values.js not available!" problem

### ISSUE THREAD

**Issue by AndreaVitale** [JoshData/jot#6]
Trying to use `build_browser_lib.js` exception 
```
	throw module_name + " not available!";
	                  ^
values.js not available!
```
is fired.
How i can solve this?

**Comment by JoshData** [comment]
Yeah that was all broken.

I've pushed all-new instructions for building for the browser --- see the README. Be sure to delete any `jot.js` file you created from the old instructions first, since that'll mess up module resolution (since it's the same name as the package.)
